diameter = input("Enter circle diameter here: ")
arc_angle = input("Enter the arc angle here: ")
radius = float(diameter) * float(0.5)
circumference = float(diameter) * float (3.14)
arc_lengthP1 = float(circumference) * float(arc_angle)
arc_length = float(arc_lengthP1) / float(360)
areaP1 = float(radius) * float(radius)
area = float(3.14) * float(areaP1)

print(radius)
print(circumference)
print(arc_length)
print(area)
print(diameter)
print(arc_angle)
print("Nice Circle!")
